AWSTemplateFormatVersion: "2010-09-09"
Description: Launch EC2 Auto Scaling

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: jahiudl-ec2-lab-launch-template
      LaunchTemplateData:
#        ImageId: ami-0c02fb55956c7d316
        InstanceType: t2.micro
        KeyName: mdjahidul-key-pair
        SecurityGroups:
          - 'MyEc2SecurityGroup'

  MyEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow ssh"
      GroupName: "MyEc2SecurityGroup"
      VpcId: vpc-08765bca90b29e055
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyDebianEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
      ImageId: ami-07d02ee1eeb0c996c
      Tags:
        - Key: "Name"
          Value: "jahidul-debian"
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyDebianEC2
Outputs:
  MyDebianEC2:
    Description: Insatnce ID
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyDebianEC2Id ] ]
    Value: !Ref MyDebianEC2
  MyDebianEC2PrivateIp:
    Description: Private IP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyDebianEC2PrivateIp ] ]
    Value: !GetAtt MyDebianEC2.PrivateIp
  MyDebianEC2EIP:
    Description:  EIP from EC2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyDebianEC2EIP ] ]
    Value: !GetAtt MyDebianEC2.PublicIp
  EIP:
    Description: EIP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, EIP ] ]
    Value: !Ref MyEIP

