AWSTemplateFormatVersion: "2010-09-09"
Description: Launch EC2 using Launch Template

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: jahiudl-ec2-lab-launch-template2
      LaunchTemplateData:
#        ImageId: ami-0c02fb55956c7d316
        InstanceType: t2.micro
        KeyName: mdjahidul-key-pair
        SecurityGroups:
          - 'MyEc2SecurityGroup'
        UserData: IyEvYmluL2Jhc2gKCmNkIC90bXAKd2dldCBodHRwczovL3MzLmFtYXpvbmF3cy5jb20vYW1hem9uY2xvdWR3YXRjaC1hZ2VudC91YnVudHUvYW1kNjQvbGF0ZXN0L2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50LmRlYgpkcGtnIC1pIC1FIC4vYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQuZGViCnRvdWNoIC9vcHQvYXdzL2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50L2V0Yy9hbWF6b24tY2xvdWR3YXRjaC1hZ2VudC5qc29uCnByaW50ZiAie1xuICBcImFnZW50XCI6IHtcbiAgICBcIm1ldHJpY3NfY29sbGVjdGlvbl9pbnRlcnZhbFwiOiA2MCxcbiAgICBcInJ1bl9hc191c2VyXCI6IFwiY3dhZ2VudFwiXG4gIH0sXG4gIFwibWV0cmljc1wiOiB7XG4gICAgXCJhcHBlbmRfZGltZW5zaW9uc1wiOiB7XG4gICAgICAgIFwiSW5zdGFuY2VJZFwiOiBcIiR7YXdzOkluc3RhbmNlSWR9XCJcbiAgICB9LFxuICAgIFwibWV0cmljc19jb2xsZWN0ZWRcIjoge1xuICAgICAgXCJkaXNrXCI6IHtcbiAgICAgICAgXCJtZWFzdXJlbWVudFwiOiBbXG4gICAgICAgICAgXCJ1c2VkX3BlcmNlbnRcIlxuICAgICAgICBdLFxuICAgICAgICBcIm1ldHJpY3NfY29sbGVjdGlvbl9pbnRlcnZhbFwiOiA2MCxcbiAgICAgICAgXCJyZXNvdXJjZXNcIjogW1xuICAgICAgICAgIFwiL1wiXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIH1cbn1cbiIgPj4gL29wdC9hd3MvYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQvZXRjL2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50Lmpzb24Kc3lzdGVtY3RsIHJlc3RhcnQgYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQK

  MyEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow ssh"
      GroupName: "MyEc2SecurityGroup"
      VpcId: vpc-06e3e15a7cb53e65f
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MyUbuntuEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
      ImageId: ami-0b0ea68c435eb488d
      Tags:
        - Key: "Name"
          Value: "jahidul-ubuntuEC2"
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyUbuntuEC2
  MyCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Permissions for CloudWatch to log custom metrics from EC2
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
  MyCloudWatchProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: myCloudWatchProfile
      Roles:
        - !Ref MyCloudWatchRole
Outputs:
  MyUbuntuEC2:
    Description: Insatnce ID
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2Id ] ]
    Value: !Ref MyUbuntuEC2
  MyUbuntuEC2PrivateIp:
    Description: Private IP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2PrivateIp ] ]
    Value: !GetAtt MyUbuntuEC2.PrivateIp
  MyUbuntuEC2EIP:
    Description:  EIP from EC2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2EIP ] ]
    Value: !GetAtt MyUbuntuEC2.PublicIp
  EIP:
    Description: EIP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, EIP ] ]
    Value: !Ref MyEIP

