AWSTemplateFormatVersion: "2010-09-09"
Description: Launch EC2 using Launch Template

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: jahiudl-ec2-lab-launch-template
      LaunchTemplateData:
#        ImageId: ami-0c02fb55956c7d316
        InstanceType: t2.micro
        KeyName: mdjahidul-key-pair
        SecurityGroups:
          - 'MyEc2SecurityGroup'

  MyEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow ssh"
      GroupName: "MyEc2SecurityGroup"
      VpcId: vpc-06e3e15a7cb53e65f
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyUbuntuEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
      ImageId: ami-04505e74c0741db8d
      Tags:
        - Key: "Name"
          Value: "jahidul-ubuntuEC2"
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyUbuntuEC2
Outputs:
  MyUbuntuEC2:
    Description: Insatnce ID
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2Id ] ]
    Value: !Ref MyUbuntuEC2
  MyUbuntuEC2PrivateIp:
    Description: Private IP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2PrivateIp ] ]
    Value: !GetAtt MyUbuntuEC2.PrivateIp
  MyUbuntuEC2EIP:
    Description:  EIP from EC2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, MyUbuntuEC2EIP ] ]
    Value: !GetAtt MyUbuntuEC2.PublicIp
  EIP:
    Description: EIP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", stack, EIP ] ]
    Value: !Ref MyEIP

