AWSTemplateFormatVersion: "2010-09-09"
Description: AWS VPC Lab
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
        - Key: Name
          Value: mdjahidul-stelligent-lab-4
        - Key: user
          Value: mdjahidul-stelligent
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.1"
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: mdjahidul-stelligent-lab-4
        - Key: user
          Value: mdjahidul-stelligent
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.1"

Outputs:
  vpcId:
    Description: The VPC ID
    Export:
      Name: MyVPCId
    Value: !Ref MyVPC
  subnetId:
    Description: The subnet ID
    Export:
      Name: MySubnetId
    Value: !Ref MySubnet