---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  Sample Template for 01-cloudformation Lab
Parameters:
  BucketName:
    Default: jahidul-01-cloudformation
    Description: S3 Bucket Name
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      #BucketName: !Ref BucketName #!Ref "AWS::Region"
      BucketName:
        !Join
        - '-'
        - - !Ref AWS::AccountId
          - !Ref BucketName
