AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  UbuntuAMI:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: '/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-02fbdc48cdb3e209b
  SubnetID:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-0ac27e2b80216ef28
  KeyName:
    Type: String
    Description: EC2 Key Pair Name
    Default: mdjahidul-key-pair
Resources:
  myLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  S3Bucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      BucketName: stelligent-u-mdjahidul.islam.labs
#      PublicAccessBlockConfiguration:
#        BlockPublicAcls: true
#        BlockPublicPolicy: true
#        IgnorePublicAcls: true
#        RestrictPublicBuckets: true

  CloudTrailLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AssumeRole1
            Effect: Allow
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'cloudtrail-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AWSCloudTrailCreateLogStream2014110
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                Resource:
                  - !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:${myLogGroup}:log-stream:${AWS::AccountId}_CloudTrail_us-east-1*'
              - Sid: AWSCloudTrailPutLogEvents20141101
                Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:${myLogGroup}:log-stream:${AWS::AccountId}_CloudTrail_us-east-1*'

  SampleBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/${Trail}'
          - Sid: AWSCloudTrailWrite20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !GetAtt Trail.Arn
                s3:x-amz-acl: bucket-owner-full-control

  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn: S3Bucket
    Properties:
      S3BucketName: !Ref S3Bucket
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      CloudWatchLogsRoleArn: !GetAtt myLogGroup.Arn
      SnsTopicName: !GetAtt myTrailTopic.TopicName
      CloudWatchLogsLogGroupArn: !GetAtt myLogGroup.Arn
      #CloudWatchLogsRoleArn:
      Tags:
        - Key: "Name"
          Value: "Jislam"
  myTrailTopic:
    Type: 'AWS::SNS::Topic'
    Properties: { }
  myTrailTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Resource: !Ref myTrailTopic
            Action: 'sns:Publish'
      Topics:
        - !Ref myTrailTopic
  mySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: mdjahidul.islam@stelligent.com
      Protocol: email
      TopicArn: !Ref myTrailTopic

Outputs:
  CloudTrailArn:
    Description: The trail ARN
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudTrailArn ] ]
    Value: !GetAtt Trail.Arn
  LogGroupArn:
    Description: LogGroup ARN
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", LogGroupArn ] ]
    Value: !GetAtt myLogGroup.Arn
