Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/mdjahidul.islam/IdeaProjects/stelligent-u/09-lambda/lambda-lab-09/hello_world
      Runtime: python3.9
      Architectures:
        - x86_64