AWSTemplateFormatVersion: "2010-09-09"
Description: AWS S3 User IAMRole3_1_1 Lab
Resources:
  MyCustomIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide readonly access to IAM
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:GenerateCredentialReport"
                  - "iam:GenerateServiceLastAccessedDetails"
                  - "iam:Get*"
                  - "iam:List*"
                  - "iam:SimulateCustomPolicy"
                  - "iam:SimulatePrincipalPolicy"
                Resource: '*'
      RoleName: CustomIAMRole

# aws cloudformation create-stack --stack-name jahidul-03-iam-lab --template-body file://IAMRole3_1_1.yaml --profile temp --capabilities CAPABILITY_NAMED_IAM